# auth_enabled: false

# server:
#   http_listen_port: 3100
#   grpc_listen_port: 9095

# common:
#   path_prefix: ./loki-data
#   storage:
#     filesystem:
#       chunks_directory: ./loki-data/chunks
#       rules_directory: ./loki-data/rules
#   replication_factor: 1
#   ring:
#     kvstore:
#       store: inmemory

# ingester:
#   chunk_idle_period: 5m
#   max_chunk_age: 1h
#   lifecycler:
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#     final_sleep: 0s

# schema_config:
#   configs:
#     - from: 2023-01-01
#       index:
#         prefix: index_
#         period: 24h
#       object_store: filesystem
#       store: tsdb
#       schema: v13

# storage_config:
#   tsdb_shipper:
#     active_index_directory: ./loki-data/index
#     cache_location: ./loki-data/tsdb-cache
#   filesystem:
#     directory: ./loki-data/chunks

# limits_config:
#   retention_period: 168h
#   allow_structured_metadata: false

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: ./loki-data
  storage:
    filesystem:
      chunks_directory: ./loki-data/chunks
      rules_directory: ./loki-data/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 5m
  max_chunk_age: 1h
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

schema_config:
  configs:
    - from: 2023-01-01
      index:
        prefix: index_
        period: 24h
      object_store: filesystem
      store: tsdb
      schema: v13

storage_config:
  tsdb_shipper:
    active_index_directory: ./loki-data/index
    cache_location: ./loki-data/tsdb-cache
  filesystem:
    directory: ./loki-data/chunks

limits_config:
  retention_period: 168h
  allow_structured_metadata: false
